version: 1

formatters:
  simple:
    format: '%(asctime)s - line %(lineno)d - %(funcName)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    maxBytes: 10485760  # 10MB
    backupCount: 20
    formatter: simple
    filename: debug.log

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    maxBytes: 10485760  # 10MB
    backupCount: 20
    formatter: simple
    filename: error.log

root:
  level: NOTSET
  handlers: [console, debug_file, error_file]